http:
  routers:
    trading-bot-http:
      rule: "Host(`fin.bykovas.lt`)"
      entryPoints:
        - web
      middlewares:
        - trading-bot-https-redirect
      service: trading-bot

    trading-bot-https:
      rule: "Host(`fin.bykovas.lt`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: trading-bot

    trading-bot-api-https:
      rule: "Host(`fin.bykovas.lt`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      priority: 20
      tls:
        certResolver: letsencrypt
      service: trading-bot-api

  middlewares:
    trading-bot-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    trading-bot:
      loadBalancer:
        servers:
          - url: "http://trading-bot-ui:80"

    trading-bot-api:
      loadBalancer:
        servers:
          - url: "http://trading-bot-api:8080"
